In [1]:
import tensorflow as tf


In [3]:
hello =tf.constant('hello world')

In [21]:
import numpy as np
import seaborn as sns 

In [12]:
np.linspace(2,10,5)

array([ 2.,  4.,  6.,  8., 10.])

In [14]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [18]:
arr=np.arange(0,11)

In [20]:
arr[:5]

array([0, 1, 2, 3, 4])

In [ ]:
df =